/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2024-06-04 13:39:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import java.math.BigDecimal;
import Tablas.Articulos;

public final class DetalleProducto_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.math.BigDecimal");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("Tablas.Articulos");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"es\">\n");
      out.write("\n");
      out.write("    <head>\n");
      out.write("        <title>ZigZag Tienda</title>\n");
      out.write("        <meta charset=\"utf-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("\n");
      out.write("        <link rel=\"apple-touch-icon\" href=\"assets/img/apple-icon.png\">\n");
      out.write("        <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"assets/img/favicon.ico\">\n");
      out.write("\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/bootstrap.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/templatemo.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/custom.css\">\n");
      out.write("\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@100;200;300;400;500;700;900&display=swap\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/fontawesome.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/slick.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/slick-theme.css\">\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\n");
      out.write("        <style>\n");
      out.write("            .widthCustom{\n");
      out.write("                width:300px;\n");
      out.write("            }\n");
      out.write("        </style>\n");
      out.write("    </head>\n");
      out.write("\n");
      out.write("    <body>\n");
      out.write("        ");

            Articulos articulo = (Articulos) request.getAttribute("articulo");
        
      out.write("\n");
      out.write("        <nav class=\"navbar navbar-expand-lg bg-dark navbar-light d-none d-lg-block\" id=\"templatemo_nav_top\">\n");
      out.write("            <div class=\"container text-light\">\n");
      out.write("                <div class=\"w-100 d-flex justify-content-between\">\n");
      out.write("                    <div>\n");
      out.write("                        <i class=\"fa fa-envelope mx-2\"></i>\n");
      out.write("                        <a class=\"navbar-sm-brand text-light text-decoration-none\" href=\"mailto:info@company.com\">Zigzag@gmail.com</a>\n");
      out.write("                        <i class=\"fa fa-phone mx-2\"></i>\n");
      out.write("                        <a class=\"navbar-sm-brand text-light text-decoration-none\" href=\"tel:010-020-0340\">+34-123-456-789</a>\n");
      out.write("                    </div>\n");
      out.write("                    <div>\n");
      out.write("                        <a class=\"text-light\" href=\"https://fb.com/templatemo\" target=\"_blank\" rel=\"sponsored\"><i class=\"fab fa-facebook-f fa-sm fa-fw me-2\"></i></a>\n");
      out.write("                        <a class=\"text-light\" href=\"https://www.instagram.com/\" target=\"_blank\"><i class=\"fab fa-instagram fa-sm fa-fw me-2\"></i></a>\n");
      out.write("                        <a class=\"text-light\" href=\"https://twitter.com/\" target=\"_blank\"><i class=\"fab fa-twitter fa-sm fa-fw me-2\"></i></a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </nav>\n");
      out.write("        <!-- Close Nav -->\n");
      out.write("\n");
      out.write("\n");
      out.write("        <!--Start Header -->\n");
      out.write("        <nav class=\"navbar navbar-expand-lg navbar-light shadow\">\n");
      out.write("            <div class=\"container d-flex justify-content-between align-items-center\">\n");
      out.write("                <img class=\"imgIconopagina\" src=\"https://cdn.icon-icons.com/icons2/3395/PNG/512/zigzag_shape_icon_214057.png\" alt=\"iconoPagina\">\n");
      out.write("                <a class=\"navbar-brand text-IconoPagina logo h1 align-self-center\" href=\"index.html\">\n");
      out.write("                    ZigZag\n");
      out.write("                </a>\n");
      out.write("\n");
      out.write("                <button class=\"navbar-toggler border-0\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#templatemo_main_nav\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("                    <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("                </button>\n");
      out.write("\n");
      out.write("                <div class=\"align-self-center collapse navbar-collapse flex-fill  d-lg-flex  flex-direct flex-row\" id=\"templatemo_main_nav\">\n");
      out.write("                    <div class=\"flex-fill\">\n");
      out.write("                        <ul class=\"nav navbar-nav d-flex justify-content-between mx-lg-auto marg-1\">\n");
      out.write("                            <li class=\"nav-item\">\n");
      out.write("                                ");
 if (session.getAttribute("usuario") != null && !session.getAttribute("usuario").equals("Trabajador1")) { 
      out.write("\n");
      out.write("                                <a class=\"nav-link\" href=\"Home2.jsp\">Home</a>\n");
      out.write("                                ");
 } else if (session.getAttribute("usuario").equals("Trabajador1")) { 
      out.write("\n");
      out.write("                                <a class=\"nav-link\" href=\"Home2Trabajador.jsp\">Home</a>\n");
      out.write("                                ");
 } else if (session.getAttribute("usuario") == null) {
      out.write("\n");
      out.write("                                <a class=\"nav-link\" href=\"Home.jsp\">Home</a>\n");
      out.write("                                ");
}
      out.write("\n");
      out.write("                            </li>\n");
      out.write("                            <li class=\"nav-item\">\n");
      out.write("                                <a class=\"nav-link\" href=\"SobreNosotros.jsp\">Sobre Nosotros</a>\n");
      out.write("                            </li>\n");
      out.write("                            <li class=\"nav-item\">\n");
      out.write("                                <a class=\"nav-link\" href=\"MostrarArticulo\">Tienda</a>\n");
      out.write("                            </li>\n");
      out.write("                            <li class=\"nav-item\">\n");
      out.write("                                <a class=\"nav-link\" href=\"contact.html\">Contacto</a>\n");
      out.write("                            </li>\n");
      out.write("                        </ul>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"navbar align-self-center d-flex \">\n");
      out.write("                        <div class=\"d-lg-none flex-sm-fill mt-3 mb-4 col-7 col-sm-auto pr-3\">\n");
      out.write("                            <div class=\"input-group\">\n");
      out.write("                                <input type=\"text\" class=\"form-control\" id=\"inputMobileSearch\" placeholder=\"Search ...\">\n");
      out.write("                                <div class=\"input-group-text\">\n");
      out.write("                                    <i class=\"fa fa-fw fa-search\"></i>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        ");

                            String usuario = (String) session.getAttribute("usuario");
                            if (usuario != null && !"Trabajador1".equals(usuario)) {
                        
      out.write("\n");
      out.write("                        <div class=\"navbar align-self-center d-flex\">\n");
      out.write("                            <div class=\"dropdown\">\n");
      out.write("                                <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"dropdownMenuLink\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\n");
      out.write("                                    ");
      out.print( usuario);
      out.write("\n");
      out.write("                                </a>\n");
      out.write("                                <ul class=\"dropdown-menu\" aria-labelledby=\"dropdownMenuLink\">\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"modificarDatos\">Modificar Datos</a></li>\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"donarRopa\">Donar Ropa</a></li>\n");
      out.write("                                        ");
 BigDecimal huchaUsuario = (BigDecimal) request.getAttribute("saldoHucha");
      out.write("\n");
      out.write("                                    <li style=\"margin-left:15px;\">");
      out.print( huchaUsuario != null ? huchaUsuario + "€" : "0.00€");
      out.write("</li>\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"cerrarSesion\">Cerrar Sesión</a></li>\n");
      out.write("                                </ul>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <a class=\"nav-icon d-none d-lg-inline\" href=\"#\" data-bs-toggle=\"modal\" data-bs-target=\"#templatemo_search\">\n");
      out.write("                            <i class=\"fas fa-shopping-cart fa-fw text-dark mr-2\"></i>\n");
      out.write("                        </a>\n");
      out.write("                        ");

                            }
                        
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </nav>\n");
      out.write("\n");
      out.write("        <section class=\"bg-light\">\n");
      out.write("            <div class=\"container pb-5\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-lg-5 mt-5\">\n");
      out.write("                        <div class=\"card mb-3\">\n");
      out.write("                            <img class=\"card-img img-fluid\" src=\"");
      out.print(articulo.getImagen());
      out.write("\" alt=\"Card image cap\" id=\"product-detail\">\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-lg-7 mt-5\">\n");
      out.write("                        <div class=\"card\">\n");
      out.write("                            <div class=\"card-body\">\n");
      out.write("                                <h1 class=\"h2\">");
      out.print(articulo.getNombre());
      out.write("</h1>\n");
      out.write("                                <p class=\"h3 py-2\">");
      out.print(articulo.getPrecio());
      out.write("</p>\n");
      out.write("                                <p class=\"py-2\">\n");
      out.write("                                    <i class=\"fa fa-star text-warning\"></i>\n");
      out.write("                                    <i class=\"fa fa-star text-warning\"></i>\n");
      out.write("                                    <i class=\"fa fa-star text-warning\"></i>\n");
      out.write("                                    <i class=\"fa fa-star text-warning\"></i>\n");
      out.write("                                    <i class=\"fa fa-star text-secondary\"></i>\n");
      out.write("                                    <span class=\"list-inline-item text-dark\">Rating 4.8 | 36 Commentarios</span>\n");
      out.write("                                </p>\n");
      out.write("\n");
      out.write("\n");
      out.write("                                <h6>Descripcion</h6>\n");
      out.write("                                <p>");
      out.print(articulo.getDescripcion());
      out.write("</p>\n");
      out.write("\n");
      out.write("                                <form action=\"\" method=\"GET\">\n");
      out.write("                                    <input type=\"hidden\" name=\"product-title\" value=\"Activewear\">\n");
      out.write("                                    ");
 String catalogo = articulo.getNombreCatalogo(); 
      out.write("\n");
      out.write("                                    ");
 if (catalogo.equals("1") || catalogo.equals("2") || catalogo.equals("3")) { 
      out.write("\n");
      out.write("                                    <div class=\"row\">\n");
      out.write("                                        <div class=\"col-auto\">\n");
      out.write("                                            <ul class=\"list-inline pb-3\">\n");
      out.write("                                                <h6>Tamaño</h6>\n");
      out.write("                                                <ul class=\"list-inline pb-3\">\n");
      out.write("                                                    ");
 List<String> tallasDisponibles = (List<String>) request.getAttribute("tallasDisponibles"); 
      out.write("\n");
      out.write("                                                    ");
 List<Integer> cantidadesDisponibles = (List<Integer>) request.getAttribute("cantidadesDisponibles"); 
      out.write("\n");
      out.write("                                                    ");
 if (tallasDisponibles != null && !tallasDisponibles.isEmpty()) { 
      out.write("\n");
      out.write("                                                    ");
 for (int i = 0; i < tallasDisponibles.size(); i++) {
      out.write("\n");
      out.write("                                                    <li class=\"list-inline-item\">\n");
      out.write("                                                        <input type=\"hidden\" name=\"product-size\" id=\"product-size\" value=\"");
      out.print( tallasDisponibles.get(i));
      out.write("\">\n");
      out.write("                                                        ");
 if (cantidadesDisponibles.get(i) > 0) {
      out.write("\n");
      out.write("                                                        <button class=\"btn btn-success btn-size\" type=\"button\" onclick=\"seleccionarTalla('");
      out.print( tallasDisponibles.get(i));
      out.write("')\">");
      out.print( tallasDisponibles.get(i));
      out.write("</button>\n");
      out.write("                                                        ");
 } else {
      out.write("\n");
      out.write("                                                        <button class=\"btn btn-secondary btn-size disabled\" type=\"button\">");
      out.print( tallasDisponibles.get(i));
      out.write("</button>\n");
      out.write("                                                        ");
 } 
      out.write("\n");
      out.write("                                                    </li>\n");
      out.write("                                                    ");
 } 
      out.write("\n");
      out.write("                                                    ");
 } else { 
      out.write("\n");
      out.write("                                                    <li class=\"list-inline-item\">No hay tallas disponibles</li>\n");
      out.write("                                                        ");
 } 
      out.write("\n");
      out.write("                                                </ul>\n");
      out.write("                                            </ul>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                    ");
 }
      out.write("\n");
      out.write("                                    <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\n");
      out.write("                                    <script>\n");
      out.write("                                                            $(document).ready(function () {\n");
      out.write("                                                                var botonCarrito = $(\"#botonCarrito\");\n");
      out.write("                                                                var catalogo = \"");
      out.print( articulo.getNombreCatalogo());
      out.write("\";\n");
      out.write("                                                                var usuarioEnSesion = \"");
      out.print( session.getAttribute("usuario"));
      out.write("\";\n");
      out.write("\n");
      out.write("                                                                if (!usuarioEnSesion) {\n");
      out.write("                                                                    botonCarrito.prop(\"disabled\", true);\n");
      out.write("                                                                }\n");
      out.write("                                                                if ((catalogo === \"4\" || catalogo === \"5\" || catalogo === \"6\" || catalogo === \"7\") && usuarioEnSesion) {\n");
      out.write("                                                                    botonCarrito.prop(\"disabled\", false);\n");
      out.write("                                                                }\n");
      out.write("                                                            });\n");
      out.write("\n");
      out.write("\n");
      out.write("                                                            function seleccionarTalla(talla) {\n");
      out.write("                                                                var botonComprar = document.getElementById(\"botonComprar\");\n");
      out.write("                                                                var idProducto = ");
      out.print( articulo.getId());
      out.write(";\n");
      out.write("                                                                var url = \"ComprarArticulo?idProducto=\" + idProducto + \"&talla=\" + encodeURIComponent(talla);\n");
      out.write("                                                                botonComprar.setAttribute(\"href\", url);\n");
      out.write("                                                                botonComprar.removeAttribute(\"disabled\");\n");
      out.write("                                                                var botonCarrito = document.getElementById(\"botonCarrito\");\n");
      out.write("                                                                botonCarrito.removeAttribute(\"disabled\");\n");
      out.write("                                                                document.getElementById(\"tallaSeleccionada\").value = talla;\n");
      out.write("                                                            }\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                                                            function verificarSeleccionTalla(event) {\n");
      out.write("                                                                var tallaSeleccionada = document.getElementById(\"tallaSeleccionada\").value;\n");
      out.write("                                                                var cantidadDisponible = ");
      out.print( articulo.getCantidadDisponible());
      out.write(";\n");
      out.write("                                                                var catalogo = ");
      out.print( articulo.getNombreCatalogo());
      out.write(";\n");
      out.write("                                                                var botonComprar = document.getElementById(\"botonComprar\");\n");
      out.write("                                                                var idProducto = ");
      out.print( articulo.getId());
      out.write(";\n");
      out.write("\n");
      out.write("                                                                if (catalogo === 4 || catalogo === 5 || catalogo === 6 || catalogo === 7) {\n");
      out.write("                                                                    var url = \"ComprarArticulo?idProducto=\" + idProducto;\n");
      out.write("                                                                    botonComprar.setAttribute(\"href\", url);\n");
      out.write("                                                                    botonComprar.removeAttribute(\"disabled\");\n");
      out.write("                                                                }\n");
      out.write("                                                                if (catalogo === 1 || catalogo === 2 || catalogo === 3) {\n");
      out.write("                                                                    if (!tallaSeleccionada) {\n");
      out.write("                                                                        event.preventDefault();\n");
      out.write("                                                                        Swal.fire({\n");
      out.write("                                                                            icon: 'warning',\n");
      out.write("                                                                            title: 'Atención',\n");
      out.write("                                                                            text: 'Por favor, selecciona una talla antes de continuar.'\n");
      out.write("                                                                        });\n");
      out.write("                                                                    }\n");
      out.write("                                                                }\n");
      out.write("\n");
      out.write("                                                                if (cantidadDisponible === 0) {\n");
      out.write("                                                                    event.preventDefault();\n");
      out.write("                                                                    Swal.fire({\n");
      out.write("                                                                        icon: 'error',\n");
      out.write("                                                                        title: 'Oops...',\n");
      out.write("                                                                        text: 'No hay artículos disponibles.'\n");
      out.write("                                                                    });\n");
      out.write("                                                                }\n");
      out.write("                                                            }\n");
      out.write("\n");
      out.write("                                                            function verificarSeleccionTalla1(event) {\n");
      out.write("                                                                var cantidadDisponible = ");
      out.print( articulo.getCantidadDisponible());
      out.write(";\n");
      out.write("                                                                var usuarioEnSesion = ");
      out.print( session.getAttribute("usuario"));
      out.write("; // Obtener el usuario en sesión\n");
      out.write("\n");
      out.write("                                                                if (!usuarioEnSesion) {\n");
      out.write("                                                                    event.preventDefault();\n");
      out.write("                                                                    Swal.fire({\n");
      out.write("                                                                        icon: 'warning',\n");
      out.write("                                                                        title: 'Atención',\n");
      out.write("                                                                        text: 'Por favor, inicia sesión antes de continuar.'\n");
      out.write("                                                                    });\n");
      out.write("                                                                } else if (cantidadDisponible === 0) {\n");
      out.write("                                                                    event.preventDefault();\n");
      out.write("                                                                    Swal.fire({\n");
      out.write("                                                                        icon: 'error',\n");
      out.write("                                                                        title: 'Oops...',\n");
      out.write("                                                                        text: 'No hay artículos disponibles.'\n");
      out.write("                                                                    });\n");
      out.write("                                                                }\n");
      out.write("                                                            }\n");
      out.write("                                    </script>\n");
      out.write("\n");
      out.write("                                    ");
 if (!(catalogo.equals("1") || catalogo.equals("2") || catalogo.equals("3"))) {
      out.write("\n");
      out.write("                                    <input type=\"hidden\" id=\"tallaSeleccionada\" value=\"");
      out.print( articulo.getCantidadDisponible());
      out.write("\">\n");
      out.write("                                    ");
 } else { 
      out.write("\n");
      out.write("                                    <input type=\"hidden\" id=\"tallaSeleccionada\" value=\"\">\n");
      out.write("                                    ");
 }
      out.write("\n");
      out.write("\n");
      out.write("                                    <h6>Cantidad Disponible</h6>\n");
      out.write("                                    <p>");
      out.print( articulo.getCantidadDisponible());
      out.write("</p>\n");
      out.write("\n");
      out.write("                                    <div class=\"row pb-3\">\n");
      out.write("                                        <div class=\"col\">\n");
      out.write("                                            <a id=\"botonComprar\" class=\"btn btn-success btn-lg widthCustom\" href=\"#\" onclick=\"verificarSeleccionTalla(event)\" disabled>Comprar</a>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"col\">\n");
      out.write("                                            <button id=\"botonCarrito\" type=\"button\" class=\"btn btn-success btn-lg widthCustom\" name=\"submit\" value=\"addtocard\" onclick=\"verificarSeleccionTalla1(event)\" disabled>Añadir al carrito</button>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </form>\n");
      out.write("\n");
      out.write("\n");
      out.write("                            </div>\n");
      out.write("                            </section>\n");
      out.write("\n");
      out.write("                            <footer class=\"bg-dark\" id=\"tempaltemo_footer\">\n");
      out.write("                                <div class=\"container\">\n");
      out.write("                                    <div class=\"row\">\n");
      out.write("\n");
      out.write("                                        <div class=\"col-md-4 pt-5\">\n");
      out.write("                                            <h2 class=\"h2 text-success border-bottom pb-3 border-light logo\">ZigZag</h2>\n");
      out.write("                                            <ul class=\"list-unstyled text-light footer-link-list\">\n");
      out.write("                                                <li>\n");
      out.write("                                                    <i class=\"fas fa-map-marker-alt fa-fw\"></i>\n");
      out.write("                                                    Calle Pamplona 4\n");
      out.write("                                                </li>\n");
      out.write("                                                <li>\n");
      out.write("                                                    <i class=\"fa fa-phone fa-fw\"></i>\n");
      out.write("                                                    <a class=\"text-decoration-none\" href=\"tel:010-020-0340\">+34-123-456-789</a>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li>\n");
      out.write("                                                    <i class=\"fa fa-envelope fa-fw\"></i>\n");
      out.write("                                                    <a class=\"text-decoration-none\" href=\"mailto:info@company.com\">ZigZag@gmail.com</a>\n");
      out.write("                                                </li>\n");
      out.write("                                            </ul>\n");
      out.write("                                        </div>\n");
      out.write("\n");
      out.write("                                        <div class=\"col-md-4 pt-5\">\n");
      out.write("                                            <h2 class=\"h2 text-light border-bottom pb-3 border-light\">Productos</h2>\n");
      out.write("                                            <ul class=\"list-unstyled text-light footer-link-list\">\n");
      out.write("                                                <li><a class=\"text-decoration-none\" href=\"shop.html\">Ropa deportiva</a></li>\n");
      out.write("                                                <li><a class=\"text-decoration-none\" href=\"shop.html\">Relojes Deportivos</a></li>\n");
      out.write("                                                <li><a class=\"text-decoration-none\" href=\"shop.html\">Articulos de lujo</a></li>\n");
      out.write("                                                <li><a class=\"text-decoration-none\" href=\"shop.html\">Zapatos Mujer</a></li>\n");
      out.write("                                                <li><a class=\"text-decoration-none\" href=\"shop.html\">Vestidos</a></li>\n");
      out.write("                                                <li><a class=\"text-decoration-none\" href=\"shop.html\">Accesorios de gym</a></li>\n");
      out.write("                                                <li><a class=\"text-decoration-none\" href=\"shop.html\">Accesorios Unisex</a></li>\n");
      out.write("                                            </ul>\n");
      out.write("                                        </div>\n");
      out.write("\n");
      out.write("                                        <div class=\"col-md-4 pt-5\">\n");
      out.write("                                            <h2 class=\"h2 text-light border-bottom pb-3 border-light\">Mas Información</h2>\n");
      out.write("                                            <ul class=\"list-unstyled text-light footer-link-list\">\n");
      out.write("                                                <li><a class=\"text-decoration-none\" href=\"index.html\">Home</a></li>\n");
      out.write("                                                <li><a class=\"text-decoration-none\" href=\"about.html\">Sobre Nosotros</a></li>\n");
      out.write("                                                <li><a class=\"text-decoration-none\" href=\"shop.html\">Tienda</a></li>\n");
      out.write("                                                <li><a class=\"text-decoration-none\" href=\"contact.html\">Contacto</a></li>\n");
      out.write("                                                <li><a class=\"text-decoration-none\" href=\"registro.html\">Registro</a></li>\n");
      out.write("                                                <li>\n");
      out.write("                                                    <a class=\"text-decoration-none\" href=\"administracion.html\"\n");
      out.write("                                                       >Sugerir Ropa</a\n");
      out.write("                                                    >\n");
      out.write("                                                </li>\n");
      out.write("                                            </ul>\n");
      out.write("                                        </div>\n");
      out.write("\n");
      out.write("                                    </div>\n");
      out.write("\n");
      out.write("                                    <div class=\"row text-light mb-4\">\n");
      out.write("                                        <div class=\"col-12 mb-3\">\n");
      out.write("                                            <div class=\"w-100 my-3 border-top border-light\"></div>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"col-auto me-auto\">\n");
      out.write("                                            <ul class=\"list-inline text-left footer-icons\">\n");
      out.write("                                                <li class=\"list-inline-item border border-light rounded-circle text-center\">\n");
      out.write("                                                    <a class=\"text-light text-decoration-none\" target=\"_blank\" href=\"http://facebook.com/\"><i class=\"fab fa-facebook-f fa-lg fa-fw\"></i></a>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li class=\"list-inline-item border border-light rounded-circle text-center\">\n");
      out.write("                                                    <a class=\"text-light text-decoration-none\" target=\"_blank\" href=\"https://www.instagram.com/\"><i class=\"fab fa-instagram fa-lg fa-fw\"></i></a>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li class=\"list-inline-item border border-light rounded-circle text-center\">\n");
      out.write("                                                    <a class=\"text-light text-decoration-none\" target=\"_blank\" href=\"https://twitter.com/\"><i class=\"fab fa-twitter fa-lg fa-fw\"></i></a>\n");
      out.write("                                                </li>\n");
      out.write("                                            </ul>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"col-auto\">\n");
      out.write("                                            <label>Siguenos para no perderte ningun articulo nuevo!</label>\n");
      out.write("                                            <label class=\"sr-only\" for=\"subscribeEmail\">Correo electronico</label>\n");
      out.write("                                            <div class=\"input-group mb-2\">\n");
      out.write("                                                <input type=\"text\" class=\"form-control bg-dark border-light\" id=\"subscribeEmail\" placeholder=\"Correo electronico\">\n");
      out.write("                                                <div class=\"input-group-text btn-success text-light\">Subscribe</div>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("\n");
      out.write("                                <div class=\"w-100 bg-black py-3\">\n");
      out.write("                                    <div class=\"container\">\n");
      out.write("                                        <div class=\"row pt-2\">\n");
      out.write("                                            <div class=\"col-12\">\n");
      out.write("                                                <p class=\"text-left text-light\">\n");
      out.write("                                                    Copyright &copy; 2024 ZigZag \n");
      out.write("                                                    | Diseñado por Danil Loginov 2ºDAW\n");
      out.write("                                                </p>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("\n");
      out.write("                            </footer>\n");
      out.write("                            <!-- End Footer -->\n");
      out.write("\n");
      out.write("                            <!-- Start Script -->\n");
      out.write("                            <script src=\"assets/js/jquery-1.11.0.min.js\"></script>\n");
      out.write("                            <script src=\"assets/js/jquery-migrate-1.2.1.min.js\"></script>\n");
      out.write("                            <script src=\"assets/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("                            <script src=\"assets/js/templatemo.js\"></script>\n");
      out.write("                            <script src=\"assets/js/custom.js\"></script>\n");
      out.write("                            <!-- End Script -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                            </body>\n");
      out.write("\n");
      out.write("                            </html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
