# Usar una imagen base de Tomcat
FROM tomcat:9.0.53-jdk11-openjdk

# Establecer el directorio de trabajo
WORKDIR /usr/local/tomcat

# Copiar el archivo WAR a la carpeta webapps de Tomcat
COPY dist/TiendaOnline.war /usr/local/tomcat/webapps/

# Exponer el puerto 8080
EXPOSE 8080

# Definir el comando de inicio
CMD ["catalina.sh", "run"]
