/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2023-11-21 09:13:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Arrays;
import modelo.Usuario;

public final class variosTema3_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:length", org.apache.taglibs.standard.functions.Functions.class, "length", new Class[] {java.lang.Object.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/camer/Desktop/2º%20DAW%20(I.E.S.%20Camas)/NetBeansProjects/Desarrollo%20web%20en%20entorno%20servidor/Tema%202/BoletinDeProblemas2/build/web/WEB-INF/lib/jstl-impl.jar!/META-INF/fn.tld", Long.valueOf(1343812618000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-impl.jar", Long.valueOf(1700557491394L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Arrays");
    _jspx_imports_classes.add("modelo.Usuario");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      modelo.Usuario usuario = null;
      synchronized (session) {
        usuario = (modelo.Usuario) _jspx_page_context.getAttribute("usuario", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (usuario == null){
          usuario = new modelo.Usuario();
          _jspx_page_context.setAttribute("usuario", usuario, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("usuario"), request);
      out.write('\n');

    if (session.getAttribute("numero") == null) {
        session.setAttribute("numero", (short) 0);
    }
    if (session.getAttribute("array") == null) {
        session.setAttribute("array", new int[10]);
    }
    short numero = (short) session.getAttribute("numero");
    numero++;
    session.setAttribute("numero", numero);
    Usuario u = (Usuario) session.getAttribute("usuario");
    // u.setNombre(u.getNombre() + "x");
    int[] array = (int[]) session.getAttribute("array");
    array[0]++;

    String[] flavours = {"chocolate", "lemon", "orange"};
    pageContext.setAttribute("flavours", flavours);

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
      out.write("        <title>Ejemplos (Tema 3)</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <!-- Acciones asociadas al manejo de beans 'include' y 'param': -->\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Cabecera" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("titulo", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("Título de la página", request.getCharacterEncoding()), out, false);
      out.write("\n");
      out.write("        <!-- Elementos de secuencias de código (expresiones): -->\n");
      out.write("        <h1>");
      out.print( session.getAttribute("numero"));
      out.write("</h1>\n");
      out.write("        ");
      out.print( u.getNombre());
      out.write("\n");
      out.write("        <br><br>\n");
      out.write("        ");
      out.print( Arrays.toString(array));
      out.write("\n");
      out.write("        <br><br>\n");
      out.write("\n");
      out.write("        <!-- Ejemplos de uso de variables en el lenguaje EL -expression language-: -->\n");
      out.write("        ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${numero}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("        <br><br>\n");
      out.write("        ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${usuario.rol}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("        ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${usuario[\"rol\"]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("        <br><br>\n");
      out.write("        <!-- En EL, si una variable devuelve un 'null', no se muestra 'null': -->\n");
      out.write("        ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${n}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("        <br><br>\n");
      out.write("        <!-- Introducir el valor del parámetro 'edad' en la URL para probar los siguientes ejemplos: -->\n");
      out.write("        <h3>Parámetro edad: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.edad}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h3>\n");
      out.write("        <h3>Parámetro edad: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param[\"edad\"]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h3>\n");
      out.write("        <br><br>\n");
      out.write("        <!-- Introducir los valores del parámetro 'usuario' en la URL para probar el siguiente ejemplo: -->\n");
      out.write("        <h3>Parámetro usuario: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${paramValues.usuario}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h3>\n");
      out.write("        <br><br>\n");
      out.write("        <!-- Introducir los valores del parámetro 'aficiones' en la URL para probar el siguiente ejemplo: -->\n");
      out.write("        <h3>Parámetro aficiones: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${paramValues.aficiones}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h3>\n");
      out.write("        <br><br>\n");
      out.write("        <h3>Cabecera Accept-Language: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${header[\"Accept-Language\"]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h3>\n");
      out.write("        <br><br>\n");
      out.write("        <h3>Cookie JSESSIONID: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cookie.JSESSIONID.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h3>\n");
      out.write("        <br><br>\n");
      out.write("        <h3>Usuario: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.usuario}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h3>\n");
      out.write("        <br><br>\n");
      out.write("        <!-- Introducir el valor del parámetro 'nombre' en la URL para probar el siguiente ejemplo: -->\n");
      out.write("        ");
      out.write("\n");
      out.write("        <!-- Introducir el valor del parámetro 'nombre' en la URL para probar el siguiente ejemplo: -->\n");
      out.write("        <h3>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.getParameter(\"nombre\")}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h3>\n");
      out.write("        <br><br>\n");
      out.write("\n");
      out.write("        <!-- Acción asociada al manejo de beans 'getProperty': -->\n");
      out.write("        Usuario: ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((modelo.Usuario)_jspx_page_context.findAttribute("usuario")).getUsuario())));
      out.write("\n");
      out.write("        <br>\n");
      out.write("        Nombre: ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((modelo.Usuario)_jspx_page_context.findAttribute("usuario")).getNombre())));
      out.write("\n");
      out.write("        <br>\n");
      out.write("        Rol: ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((modelo.Usuario)_jspx_page_context.findAttribute("usuario")).getRol())));
      out.write("\n");
      out.write("        <br><br>\n");
      out.write("\n");
      out.write("        <!-- Ejemplos de uso de las 'EL functions': -->\n");
      out.write("        <p>Tenemos ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:length(pageContext.request.parameterNames)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write(" parámetros en la petición.</p>\n");
      out.write("        <p>Tenemos ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:length(flavours)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write(" sabores de helado.</p>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
